### ISSUE TITLE
audio output.

### ISSUE THREAD

**Issue by Greg0059** [yuliskov/SmartTubeNext#709] opened 2021-06-25 23:35 UTC
is there Dolby Atmos 5.1 and 7.1 output.

**Comment by SyCoREAPER** [comment] 2021-06-26 00:25
There is. The issue is it doesn't select it by default. 

opus is superior in audio quality but mp4a is the only one that has 5.1. 

More comprehensive default audio would be nice. If 5.1 is available it would be nice if it auto selected it and reverts back to opus on next video

**Comment by Greg0059** [comment] 2021-06-26 01:23
Thank you for replying so quickly  and with good information



Sent from my Galaxy



-------- Original message --------
From: SyCoREAPER ***@***.***>
Date: 26/06/21 12:25 (GMT+12:00)
To: yuliskov/SmartTubeNext ***@***.***>
Cc: Greg0059 ***@***.***>, Author ***@***.***>
Subject: Re: [yuliskov/SmartTubeNext] audio output. (#709)


There is. The issue is it doesn't select it by default.

opus is superior in audio quality but mp4a is the only one that has 5.1.

More comprehensive default audio would be nice. If 5.1 is available it would be nice if it auto selected it and reverts back to opus on next video

**Comment by Grauen** [comment] 2021-06-27 00:00
@Greg0059 then you should close the issue.

**Comment by Greg0059** [comment] 2021-06-27 00:08
Thank you  issue fixed

**Closed** 2021-06-27 00:07 UTC
