### ISSUE TITLE
Feature request: Add SponsorBlock to app

### ISSUE THREAD

**Issue by Thorondor2011** [yuliskov/SmartTubeNext#173] opened 2020-11-21 19:19 UTC
From the website [https://sponsor.ajay.app/](https://sponsor.ajay.app/) :
_SponsorBlock is an open-source crowdsourced browser extension and open API for skipping sponsor segments in YouTube videos. Users submit when a sponsor happens from the extension, and the extension automatically skips sponsors it knows about. It also supports skipping other categories, such as intros, outros and reminders to subscribe._

I use it on my phone in Youtube Vanced. It's amazing.

**Comment by kuafor41** [comment] 2020-11-22 11:43
Do you know is there any ATV version of YouTube Vanced too ?

**Comment by Thorondor2011** [comment] 2020-11-22 12:40
No I didn't. When I looked for the ATV version I came across this project instead. Could you provide a link to it? I can't find it nor any mention of it on the Vanced website. I force installed it through the Vanced Manager, but the app won't show anywhere on my TV.

**Comment by kuafor41** [comment] 2020-11-22 16:30
So this means it must be phone spesific app. Maybe you can sideload necassary APKs and try.

**Comment by andrewjmetzger** [comment] 2020-11-25 05:53
YouTube Vanced works well enough if sideloaded (try installing [Vanced Manager](https://vancedmanager.com/), which should give you a compatible version of YT Vanced), although a keyboard or an airmouse remote is advised for ease-of-use. I would really like to see SponsorBlock integrated into this project for native Android TV compatibility

See also, issue #11.

**Comment by WeslyG** [comment] 2020-11-27 17:42
here is a link to the official website of the project, if it is still relevant https://sponsor.ajay.app/

**Comment by andrewjmetzger** [comment] 2020-11-27 21:20
Thanks WeslyG. :) It's also linked in the opening comment, https://github.com/yuliskov/SmartTubeNext/issues/173#issue-748085477

**Comment by rodalpho** [comment] 2020-11-30 17:24
Yes, this feature was declined for SYTV, hopefully it'll be accepted now!

**Comment by fawzib** [comment] 2020-12-11 19:06
please close this thread and merge it with this https://github.com/yuliskov/SmartTubeNext/issues/11

**Comment by Rudde** [comment] 2020-12-24 11:40
This feature isn't only about sponsorship skips either. It's GREAT for music video playlists on parties, since it skip non-music parts automatically. This would be absolutely amazing at any party on the big screen.

**Comment by DraconicNEO** [comment] 2021-01-08 02:29
This is a duplicate of #11

**Comment by foreveryoungforty** [comment] 2021-01-26 07:49
@Thorondor2011 implemented in new update - please close this issue.

**Closed** 2021-01-26 07:55 UTC
