### ISSUE TITLE
Casting not working after latest update.

### ISSUE THREAD

**Issue by Zyybolt** [yuliskov/SmartTubeNext#1145] opened 2021-12-19 23:23 UTC
SmartTubeNext is no longer showing up in the cast list. Tried on several devices.

**Comment by rhetsigga** [comment] 2021-12-27 03:03
Same for me, except it works the first time and then every time after it doesn't connect. It doesn't appear on the list of devices (only the regular Youtube does). And when I try add it again, it will make a connection but won't connect - The cast icon sort of animates continuously.

**Comment by AlexeSimon** [comment] 2021-12-30 22:24
might be a duplicate of https://github.com/yuliskov/SmartTubeNext/issues/1066

**Comment by rhetsigga** [comment] 2021-12-31 18:44
> might be a duplicate of #1066

Yes I'm sure it is

**Closed** 2021-12-31 21:34 UTC
