### ISSUE TITLE
View videos in a playlist

### ISSUE THREAD

**Issue by Wolf68k** [yuliskov/SmartTubeNext#1083] opened 2021-11-25 18:55 UTC
For a short time if went to a channel or did a search and found a playlist then clicked on it, I would see a list of the videos in that playlist. I loved it. It made it so much easier to find a video I wanted to watch. 

Now it seems that is gone and it's back to the original way which is click on a playlist and it plays the first video, which sucks and really damn annoying. If I want to watch a video in the middle of the playlist I have look at the first row of suggested videos and then hope the video I want to see is listed. I also have to hope they are in the right order, which isn't always the case.

The only thing close to that what it shortly once was is; select the playlist, bring up the menu and select Open Channel which then options the list of video for that playlist. Just two little problems; one is that is oddly worded then, and two it'll always open in a grid. What happened before was that the playlist would list the videos in a row. I wouldn't have too much of a problem with that either way but give an option for it.

Speaking of options, if people want it so they click on a playlist from another channel and it just plays the first video, fine. But then you have people like me that want to see the list of videos. So give everyone that option of what happens when we click the playlist and how that list is displayed.

Side note, the Pin/Unpin From Sidebar is missing for playlists other than my own.

**Comment by costinmx** [comment] 2021-11-25 22:15
I totally agree with this. Why are all the good things keep being reverted from this app? (also #1007) Now there's another: Autoplay the first clip on every playlist you click on - it's so useless... The app was SO FINE at some point. Almost perfect. Unfortunately there are a lot of lazy people here who are demanding all this sort of changes, so they would not have to press an extra key.... And a lot of good work goes down the drain, again...
I had to revert all the way to v12.99 to get rid of already so many "dis"improvements. It's the latest working fine version with all good options included. 
@yuliskov : Cannot at least make some of this changes, like "autoplay of the playlists", optional?

**Comment by costinmx** [comment] 2021-12-01 08:11
It appears fixed in STN Beta v13.55. Clicking on the playlist card, opens the playlist. It's not autoplaying the first video anymore. 
If you agree, I may suggest closing the issue.

**Comment by Wolf68k** [comment] 2021-12-01 19:21
That part is fixed. Still can't pin a playlist though. Maybe I should make a separate "issue" for that?

**Comment by costinmx** [comment] 2021-12-01 20:16
I didn't noticed any issue with pinning playlists on the sidebar. You just have to make sure you pin the playlist card in Grid Mode. It's working for me.

**Comment by Wolf68k** [comment] 2021-12-01 22:25
Are you trying this on your own playlists or another channel's playlist?

**Comment by costinmx** [comment] 2021-12-02 01:28
You are right. There are still 2 problems:
First, the context menu 'Pin to sidebar' is missing when called from other's playlist cards. Own playlists working fine...
Second, returning from a viewed playlist (pressing Back), results in a BLACK screen instead of the previous page. 

I hope @yuliskov still sees this thread. I suggest you may edit the issue title to something like "Viewing playlist & sidebar pinning issues in v13.57".....

**Comment by Wolf68k** [comment] 2021-12-02 01:36
It took me a moment to understand what you mean about the black screen.
When on another channel, open their playlist, then press back, the screen goes black instead of returning you to the channel.
This does not happen when opening a playlist found as a search result.

This is happening on 13.57 (and in case it matters) on Fire TV.

**Comment by costinmx** [comment] 2021-12-02 01:48
> This does not happen when opening a playlist found as a search result.

And that's a third issue: For me, when playlist is opened from a search result, it autoplays the first video. So the issue is still not fully solved. I'm on Android TV.  V13.57, also

**Comment by costinmx** [comment] 2021-12-02 14:06
Second issue (black screen) was solved in 13.58. 

Pinning issue is more complex. Older playlists CAN be pinned via context menu, but in newer ones the context menu is missing. They cannot be pinned. That's a strange behaviour.

**Comment by costinmx** [comment] 2021-12-17 20:57
This issue looks solved in latest updates. Everything is working fine now.
From my POV, this topic may be closed. Just like #1094

**Closed** 2022-01-02 13:19 UTC
